# Generated by Django 3.1.7 on 2021-03-15 18:43

from django.db import migrations, models
from web.mixins.models import StatusModel

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSeaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=StatusModel.STATUS_CODES, default=1, null=True, verbose_name='status')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('meta', models.JSONField(help_text='See all available Metadata here https://docs.opensea.io/docs/metadata-standards)')),
            ],
            options={
                'verbose_name': 'Open Sea Item',
                'verbose_name_plural': 'Open Sea Items',
            },
        ),
    ]
