# Generated by Django 3.1.7 on 2021-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openseaitem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openseaitem',
            name='meta',
            field=models.JSONField(help_text='See all available Metadata <a href="https://docs.opensea.io/docs/metadata-standards">here</a>'),
        ),
    ]
